### PR TITLE
v3.2.0 (add SFTP support)

### PR DESCRIPTION
**Pull request by damnski**
Add support for SFTP protocol transfers, break out SFTP from SCP.  Add more tcl error* output in try/catch for SFTP and SCP.

### CODE REVIEW

**Comment by damnski** [comment]
I know a response will be you can use the scp client for SFTP connections.  I have not been successful with this.  Particularly, I am getting this error with using scp as a client for the SFTP server with AWS transfers/SFTP which is a black box implementation, and they strictly only support SFTP.
"Could not chdir to home directory /dev/null: Not a directory"

**Comment by damnski** [comment]
tap tap tap - this thing on?

**Comment by f5-rahm** [comment]
@damnski I forked your fork to the f5devcentral org and merged your 3.2 to master and updated links to DC resources so they don't 404.

**Comment by damnski** [comment]
kewl, thx!

**Comment by tabernarious** [comment]
Awesome! Thanks Darryl and Jason. -Daniel

**Pull request closed without merging**
